# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6637de237870690972089dac927637fa94a28fe0d94243d73bdd094d037ac156754d2ca2d381709ec620f05341ef8c3ff60d576b5da0a23f1585cc7200dbf546

test:
  secret_key_base: 9705e8a8ba5fc4b2817f1441dbf75015088b93602ee73d8156cf743343d57e2ccf2f59f935b52e4b2205a74203e2b15a1e15b6266eb34de4f935f14d0d01df26

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
